services:
  - type: web
    name: dotacion-reportes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 300 --graceful-timeout 300
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dotacion-reportes-db
          property: connectionString
      - key: MAX_CONTENT_LENGTH_MB
        value: 80

databases:
  - name: dotacion-reportes-db
